/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2labp2_andreflores;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author andre
 */
// FILA 3 ASIENTO 10
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCreacion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        botonBienvenido1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_marca1 = new javax.swing.JTextField();
        tf_modelo1 = new javax.swing.JTextField();
        sp_velocidad1 = new javax.swing.JSpinner();
        BotonCrear1 = new javax.swing.JButton();
        jd_Carrera = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        pb2 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        tfPCarro1 = new javax.swing.JTextField();
        tfP_Carro2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearCarroMain = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cb_Carros1 = new javax.swing.JComboBox<>();
        cb_Carros2 = new javax.swing.JComboBox<>();
        btn_IniciarCarrera = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tfMarca1 = new javax.swing.JTextField();
        tfMarca2 = new javax.swing.JTextField();
        tf_Modelo1 = new javax.swing.JTextField();
        tf_Modelo2 = new javax.swing.JTextField();
        tf_Velocidad2 = new javax.swing.JTextField();
        tf_Velocidad1 = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBienvenido1.setText("Bienvenido");
        botonBienvenido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBienvenido1MouseClicked(evt);
            }
        });
        jPanel2.add(botonBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Creacion de Carros");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Velocidad");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Marca");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modelo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        tf_marca1.setBackground(new java.awt.Color(255, 255, 255));
        tf_marca1.setForeground(new java.awt.Color(0, 0, 0));
        tf_marca1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(tf_marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, 50));

        tf_modelo1.setBackground(new java.awt.Color(255, 255, 255));
        tf_modelo1.setForeground(new java.awt.Color(0, 0, 0));
        tf_modelo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(tf_modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 220, 50));

        sp_velocidad1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        sp_velocidad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(sp_velocidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 200, 60));

        BotonCrear1.setBackground(new java.awt.Color(255, 255, 255));
        BotonCrear1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotonCrear1.setForeground(new java.awt.Color(0, 0, 0));
        BotonCrear1.setText("Crear");
        BotonCrear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonCrear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCrear1MouseClicked(evt);
            }
        });
        jPanel2.add(BotonCrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 110, 60));

        javax.swing.GroupLayout jdCreacionLayout = new javax.swing.GroupLayout(jdCreacion.getContentPane());
        jdCreacion.getContentPane().setLayout(jdCreacionLayout);
        jdCreacionLayout.setHorizontalGroup(
            jdCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdCreacionLayout.setVerticalGroup(
            jdCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tiempo");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Progreso");

        pb1.setMaximum(1000);

        pb2.setMaximum(1000);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("A Correr");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        tfPCarro1.setEditable(false);

        tfP_Carro2.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfPCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(tfP_Carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(tfP_Carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jd_CarreraLayout = new javax.swing.GroupLayout(jd_Carrera.getContentPane());
        jd_Carrera.getContentPane().setLayout(jd_CarreraLayout);
        jd_CarreraLayout.setHorizontalGroup(
            jd_CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CarreraLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_CarreraLayout.setVerticalGroup(
            jd_CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Partida");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 50));

        btnCrearCarroMain.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearCarroMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearCarroMain.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearCarroMain.setText("Crear Carro");
        btnCrearCarroMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearCarroMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCarroMainMouseClicked(evt);
            }
        });
        jPanel3.add(btnCrearCarroMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 110, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jugador 1");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Modelo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Velocidad");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Velocidad");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Marca");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Modelo");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Jugador 1");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        cb_Carros1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Carros1ItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_Carros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 50));

        cb_Carros2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Carros2ItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_Carros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 140, 180, 50));

        btn_IniciarCarrera.setBackground(new java.awt.Color(255, 255, 255));
        btn_IniciarCarrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_IniciarCarrera.setForeground(new java.awt.Color(0, 0, 0));
        btn_IniciarCarrera.setText("Iniciar");
        btn_IniciarCarrera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_IniciarCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IniciarCarreraMouseClicked(evt);
            }
        });
        jPanel3.add(btn_IniciarCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 80, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cargar Carros");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 40));

        tfMarca1.setEditable(false);
        jPanel3.add(tfMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 40));

        tfMarca2.setEditable(false);
        jPanel3.add(tfMarca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 40));

        tf_Modelo1.setEditable(false);
        jPanel3.add(tf_Modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 40));

        tf_Modelo2.setEditable(false);
        jPanel3.add(tf_Modelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 100, 40));

        tf_Velocidad2.setEditable(false);
        jPanel3.add(tf_Velocidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 462, 100, 40));

        tf_Velocidad1.setEditable(false);
        jPanel3.add(tf_Velocidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBienvenido1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBienvenido1MouseClicked
        try {
            FileInputStream direccion;

            File file = new File("src/Bienvenido a Doc Tops Sound.MP3");
            direccion = new FileInputStream(file.getAbsolutePath());
            Player player;
            BufferedInputStream bis = new BufferedInputStream(direccion);
            player = new Player(bis);
            player.play();

        } catch (JavaLayerException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_botonBienvenido1MouseClicked

    private void btnCrearCarroMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCarroMainMouseClicked
        this.setVisible(false);
        jdCreacion.pack();
        jdCreacion.setLocationRelativeTo(this);
        jdCreacion.setVisible(true);
        jdCreacion.setResizable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCarroMainMouseClicked

    private void btn_IniciarCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IniciarCarreraMouseClicked
        if (carros.size() > 0) {
            this.setVisible(false);
            jd_Carrera.pack();
            jd_Carrera.setLocationRelativeTo(this);
            jd_Carrera.setVisible(true);
            jd_Carrera.setResizable(false);
        } else {
            JOptionPane.showMessageDialog(this, "no hay suficientes carros para correr");
        }


    }//GEN-LAST:event_btn_IniciarCarreraMouseClicked

    private void BotonCrear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCrear1MouseClicked
        String marca = tf_marca1.getText();
        String modelo = tf_modelo1.getText();
        int velocidad = (int) sp_velocidad1.getValue();

        carros.add(new Carro(marca, modelo, velocidad));
        escribirCarros(carros, "Carros.bin");
        System.out.println(carros);
        jdCreacion.setVisible(false);
        this.pack();
        this.setVisible(true);
        this.setResizable(false);
    }//GEN-LAST:event_BotonCrear1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        carros = leerCarros("Carros.bin");

        DefaultComboBoxModel nuevom1 = new DefaultComboBoxModel();
        DefaultComboBoxModel nuevom2 = new DefaultComboBoxModel();
        cb_Carros1.setModel(nuevom1);
        cb_Carros2.setModel(nuevom2);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Carros1.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Carros2.getModel();
        boolean carroAgregado = false;

        for (Carro carro : carros) {
            modelo.addElement(carro);
            modelo2.addElement(carro);
        }
        cb_Carros1.setModel(modelo);
        cb_Carros2.setModel(modelo2);

    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_Carros1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Carros1ItemStateChanged
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Carros1.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_Carros2.getModel();
        Carro carroescogido = (Carro) cb_Carros1.getSelectedItem();
        tfMarca1.setText(carroescogido.getMarca());
        tf_Modelo1.setText(carroescogido.getModelo());
        tf_Velocidad1.setText(String.valueOf(carroescogido.getVelocidad()));
        tfPCarro1.setText(carroescogido.getMarca() + " " + carroescogido.getModelo());

// TODO add your handling code here:
    }//GEN-LAST:event_cb_Carros1ItemStateChanged

    private void cb_Carros2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Carros2ItemStateChanged
        Carro carroescogido2 = (Carro) cb_Carros2.getSelectedItem();
        tfMarca2.setText(carroescogido2.getMarca());
        tf_Modelo2.setText(carroescogido2.getModelo());
        tf_Velocidad2.setText(String.valueOf(carroescogido2.getVelocidad()));
        tfP_Carro2.setText(carroescogido2.getMarca() + " " + carroescogido2.getModelo());

        // TODO add your handling code here:
    }//GEN-LAST:event_cb_Carros2ItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Carro carroescogido = (Carro) cb_Carros1.getSelectedItem();

        Carro carroescogido2 = (Carro) cb_Carros2.getSelectedItem();

        hilobarras = new HiloProgressbar(pb1, pb2, carroescogido.getVelocidad(), carroescogido2.getVelocidad(), jLabel17);
        hilobarras.start();

    }//GEN-LAST:event_jButton2MouseClicked
    public static void escribirCarros(ArrayList<Carro> carros, String nombreArchivo) {
        try (ObjectOutputStream OOS = new ObjectOutputStream(new FileOutputStream(nombreArchivo))) {
            OOS.writeObject(carros);
            System.out.println("guarddo");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static ArrayList<Carro> leerCarros(String nombreArchivo) {
        ArrayList<Carro> usuarios = new ArrayList();
        try (ObjectInputStream OIS = new ObjectInputStream(new FileInputStream(nombreArchivo))) {
            usuarios = (ArrayList<Carro>) OIS.readObject();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return usuarios;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrear1;
    private javax.swing.JButton botonBienvenido1;
    private javax.swing.JButton btnCrearCarroMain;
    private javax.swing.JButton btn_IniciarCarrera;
    private javax.swing.JComboBox<String> cb_Carros1;
    private javax.swing.JComboBox<String> cb_Carros2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog jdCreacion;
    private javax.swing.JDialog jd_Carrera;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JSpinner sp_velocidad1;
    private javax.swing.JTextField tfMarca1;
    private javax.swing.JTextField tfMarca2;
    private javax.swing.JTextField tfPCarro1;
    private javax.swing.JTextField tfP_Carro2;
    private javax.swing.JTextField tf_Modelo1;
    private javax.swing.JTextField tf_Modelo2;
    private javax.swing.JTextField tf_Velocidad1;
    private javax.swing.JTextField tf_Velocidad2;
    private javax.swing.JTextField tf_marca1;
    private javax.swing.JTextField tf_modelo1;
    // End of variables declaration//GEN-END:variables
ArrayList<Carro> carros = new ArrayList();
    HiloProgressbar hilobarras;
}
